### ISSUE TITLE
did it real work

### ISSUE THREAD

**Issue by jboubb** [randomwons/WSL2-USB-Camera#1]
did it real work??
my wsl just Can't start
：（
没有收到虚拟机或容器的回应，操作超时。
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT

even I try many ways like：
start LxssManager
LxssManager 服务正在启动 .
LxssManager 服务已经启动成功。

now I give up to use wsl to connect usb camer

**Comment by randomwons** [comment]
Sorry! I just saw this now.

Are you still having trouble with this issue?

I've fixed a few problems and uploaded a tutorial video.
If you haven't figured it out yet, please refer to it.

Thank you.

**Comment by jboubb** [comment]
Thank you for your reply. I successfully realized the function I wanted by using other people's wsl-usbcam project on github.
Your project is still very helpful. I hope you can help more people.
